apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: ${{ values.component_id }}-sa
  annotations:
    cnrm.cloud.google.com/project-id: ${{ values.gcp_project_id }}
spec:
  displayName: "${{ values.component_id }} Service Account"
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: ${{ values.component_id }}-storage-access
  annotations:
    cnrm.cloud.google.com/project-id: ${{ values.gcp_project_id }}
spec:
  member: serviceAccount:${{ values.component_id }}-sa@${{ values.gcp_project_id }}.iam.gserviceaccount.com
  role: roles/storage.objectUser
  resourceRef:
    kind: StorageBucket
    name: ${{ values.component_id }}-data
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: ${{ values.component_id }}-vertex-access
  annotations:
    cnrm.cloud.google.com/project-id: ${{ values.gcp_project_id }}
spec:
  member: serviceAccount:${{ values.component_id }}-sa@${{ values.gcp_project_id }}.iam.gserviceaccount.com
  role: roles/aiplatform.user
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: projects/${{ values.gcp_project_id }}
