apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  name: ${{ values.component_id }}-data
  labels:
    managed-by: backstage
    cost-center: ai-research
    environment: ${{ values.environment }}
spec:
  location: EU
  uniformBucketLevelAccess: true
  versioning:
    enabled: true
  lifecycle:
    rule:
      - action:
          type: Delete
        condition:
          age: 365
