apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: genai-gitlab-template
  title: GenAI RAG Application (GitLab)
  description: |
    Provision a secured Vertex AI environment with:
    - GCS Storage Bucket for data
    - Vertex AI API enabled
    - Service Account with proper IAM
    - Streamlit chatbot UI
  tags:
    - gcp
    - vertex-ai
    - gitlab
    - python
    - genai
spec:
  owner: platform-team
  type: service

  parameters:
    - title: Application Metadata
      required:
        - component_id
        - description
        - owner
      properties:
        component_id:
          title: Service Name
          type: string
          description: Unique identifier for your service (e.g., 'forecasting-bot-v1')
          pattern: '^[a-z0-9-]+$'
          ui:field: EntityNamePicker
          ui:autofocus: true
        description:
          title: Description
          type: string
          description: Brief description of what this GenAI service does
          default: A new GenAI experiment
        owner:
          title: Owner
          type: string
          description: Team or user responsible for this service
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              kind: Group

    - title: Infrastructure Configuration
      required:
        - gcp_project_id
        - gcp_region
      properties:
        gcp_project_id:
          title: Google Cloud Project ID
          type: string
          description: The GCP project where resources will be created and billed
        gcp_region:
          title: GCP Region
          type: string
          description: Region for Vertex AI resources
          default: us-central1
          enum:
            - us-central1
            - us-east1
            - us-west1
            - europe-west1
            - europe-west4
            - asia-northeast1
          enumNames:
            - US Central (Iowa)
            - US East (South Carolina)
            - US West (Oregon)
            - Europe West (Belgium)
            - Europe West (Netherlands)
            - Asia Northeast (Tokyo)
        environment:
          title: Environment
          type: string
          description: Deployment environment
          default: development
          enum:
            - development
            - staging
            - production

    - title: Repository Configuration
      required:
        - repoOwner
      properties:
        repoOwner:
          title: GitLab Group/User
          type: string
          description: The GitLab namespace where the repository will be created (must match the ArgoCD ApplicationSet group for auto-discovery)
        repoVisibility:
          title: Repository Visibility
          type: string
          default: private
          enum:
            - private
            - internal
            - public

  steps:
    - id: fetch-base
      name: Fetching Blueprint
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutTemplating:
          - '**/*.png'
          - '**/*.ico'
        values:
          component_id: ${{ parameters.component_id }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner }}
          gcp_project_id: ${{ parameters.gcp_project_id }}
          gcp_region: ${{ parameters.gcp_region }}
          environment: ${{ parameters.environment }}
          repoOwner: ${{ parameters.repoOwner }}

    - id: publish
      name: Publishing to GitLab
      action: publish:gitlab
      input:
        repoUrl: gitlab.com?owner=${{ parameters.repoOwner }}&repo=${{ parameters.component_id }}
        defaultBranch: main
        repoVisibility: ${{ parameters.repoVisibility }}

    - id: register
      name: Registering in Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml

  output:
    links:
      - title: Source Code Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Open in Catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
      - title: GCP Console
        url: https://console.cloud.google.com/home/dashboard?project=${{ parameters.gcp_project_id }}
      - title: Vertex AI Console
        url: https://console.cloud.google.com/vertex-ai?project=${{ parameters.gcp_project_id }}
